import React, { memo } from "react";

const AISummaryPanel = memo(function AISummaryPanel({ summaryData }) {
  const defaultSummary = {
    executiveSummary: "Overall system reliability remains stable at 99.82%. However, machine learning ensemble models forecast a 78% probability of API Gateway degradation within the next 12 hours due to unoptimized database connection pool limits during peak trading hours.",
    operationalSummary: "Active telemetry indicates increased query queue times in PostgreSQL primary cluster. CPU usage is operating within 62% normal capacity, but memory buffers are approaching 84% utilization.",
    topRisks: [
      "Database connection pool starvation during 09:00 AM traffic surge",
      "API Gateway latency exceeding 500ms target SLA",
      "Payment Webhook timeout impacting Enterprise tier checkout",
    ],
    immediateActions: [
      "Increase PgBouncer max_client_conn limit to 250",
      "Pre-scale API Gateway replica pods from 8 to 16",
      "Flush Redis cache key namespace 'session_tokens_v2'",
    ],
    weeklyForecast: "Expected 14 total incidents over the next 7 days, primarily concentrated in peak business hours (Tuesday & Thursday). Expected resolution time per incident: 18 minutes.",
  };

  const summary = summaryData || defaultSummary;

  return (
    <div className="panel ai-summary-panel" role="region" aria-label="Gemini AI Summary">
      <div className="panel-header">
        <div>
          <h2>🤖 Gemini AI Executive & Operational Intelligence Summary</h2>
          <p>Real-time automated narrative synthesis generated by Google Gemini AI ensemble models.</p>
        </div>
        <span className="ai-live-badge">✨ Live AI Synthesis</span>
      </div>

      <div className="ai-summary-grid">
        <div className="summary-block exec-summary-block">
          <h3>📌 Executive Summary</h3>
          <p>{summary.executiveSummary}</p>
        </div>

        <div className="summary-block op-summary-block">
          <h3>⚙️ Operational Summary</h3>
          <p>{summary.operationalSummary}</p>
        </div>

        <div className="summary-block top-risks-block">
          <h3>⚠️ Top Identified Risks</h3>
          <ul>
            {summary.topRisks.map((risk, idx) => (
              <li key={idx}>{risk}</li>
            ))}
          </ul>
        </div>

        <div className="summary-block actions-block">
          <h3>🚀 Immediate Recommended Actions</h3>
          <ol>
            {summary.immediateActions.map((action, idx) => (
              <li key={idx}>{action}</li>
            ))}
          </ol>
        </div>

        <div className="summary-block forecast-block full-width">
          <h3>📅 7-Day Reliability & Outage Forecast</h3>
          <p>{summary.weeklyForecast}</p>
        </div>
      </div>
    </div>
  );
});

export default AISummaryPanel;
