import React, { memo } from "react";

const PredictiveRecommendations = memo(function PredictiveRecommendations({ recommendations = [] }) {
  const defaultRecommendations = [
    {
      id: "rec-1",
      title: "Scale PostgreSQL Connection Pool & Reindex Telemetry",
      recommendation: "Increase database pool size limit from 100 to 250 connections and execute background index creation on high-cardinality foreign keys.",
      priority: "HIGH",
      category: "OPERATIONAL_PREVENTATIVE",
      impact_score: "85/100 Risk Reduction",
      confidence: 94,
      affectedServices: "Database, Ingestion Pipeline",
    },
    {
      id: "rec-2",
      title: "Enable Circuit Breaker on API Gateway Ingestion",
      recommendation: "Configure automatic rate-limiting and fallback queuing on incoming webhook ingestion endpoints to prevent memory starvation during spikes.",
      priority: "HIGH",
      category: "INFRASTRUCTURE",
      impact_score: "78/100 Risk Reduction",
      confidence: 89,
      affectedServices: "API Gateway, Webhook Listener",
    },
    {
      id: "rec-3",
      title: "Flush Stale Keys & Scale Redis Node Replica",
      recommendation: "Execute proactive TTL audit on Redis session keys and add a secondary read replica to distribute caching load during peak billing hours.",
      priority: "MEDIUM",
      category: "DATABASE_PERFORMANCE",
      impact_score: "62/100 Risk Reduction",
      confidence: 82,
      affectedServices: "Redis Cache, User Auth",
    },
  ];

  const recs = recommendations.length > 0 ? recommendations : defaultRecommendations;

  return (
    <div className="panel predictive-recs-panel" role="region" aria-label="AI Automated Mitigation Recommendations">
      <div className="panel-header">
        <div>
          <h2>💡 AI Prescriptive Action Recommendations</h2>
          <p>Automated preventative actions generated by Gemini AI to mitigate forecasted anomalies before SLA impact.</p>
        </div>
      </div>

      <div className="recommendations-list">
        {recs.map((rec) => (
          <div key={rec.id} className={`recommendation-item priority-${(rec.priority || "HIGH").toLowerCase()}`}>
            <div className="rec-header">
              <div className="rec-title-block">
                <span className={`priority-badge prio-${(rec.priority || "HIGH").toLowerCase()}`}>
                  {rec.priority || "HIGH"} PRIORITY
                </span>
                <h4 className="rec-title">{rec.title || `Preemptive Action for ${rec.kpi_name}`}</h4>
              </div>
              <span className="rec-confidence-pill">🎯 {rec.confidence || 90}% Confidence</span>
            </div>

            <p className="rec-body-text">{rec.recommendation}</p>

            <div className="rec-footer-grid">
              <div className="rec-meta-cell">
                <span className="rec-meta-label">Est. Business Impact</span>
                <span className="rec-meta-val green-val">✨ {rec.impact_score || "80/100 Risk Reduction"}</span>
              </div>

              <div className="rec-meta-cell">
                <span className="rec-meta-label">Affected Services</span>
                <span className="rec-meta-val">{rec.affectedServices || rec.department || "Infrastructure"}</span>
              </div>

              <div className="rec-meta-cell align-right">
                <button className="primary-button small-btn" onClick={() => alert(`Initiated automated mitigation task: ${rec.title}`)}>
                  ▶ Execute Automated Mitigation
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
});

export default PredictiveRecommendations;
