import React from "react";

export default function RecommendationsTab({ recommendations }) {
  return (
    <div className="tab-content recommendations-tab">
      <div className="tab-control-bar">
        <p className="tab-lead-text">
          AI-generated executive business recommendations to mitigate projected risks before operational impact.
        </p>
        <span className="count-badge">{recommendations.length} Action Plan(s)</span>
      </div>

      <div className="panel">
        <div className="panel-header">
          <div>
            <h2>Executive Action Plans & Preventative Guidance</h2>
            <p>Generated by AI engine based on metric trajectory and department context.</p>
          </div>
        </div>

        {recommendations.length > 0 ? (
          <div className="recommendations-list">
            {recommendations.map((rec) => (
              <div className="recommendation-card" key={rec.id}>
                <div className="rec-card-header">
                  <div className="rec-title-group">
                    <span className={`priority-badge ${(rec.priority || "").toLowerCase()}`}>
                      {rec.priority} PRIORITY
                    </span>
                    <h3>{rec.title}</h3>
                  </div>
                  <span className="impact-score-tag">{rec.impact_score}</span>
                </div>

                <div className="rec-card-body">
                  <div className="rec-meta-row">
                    <span>Department: <strong>{rec.department}</strong></span>
                    <span>Target KPI: <strong>{rec.kpi_name}</strong></span>
                    <span>Category: <code>{rec.category}</code></span>
                  </div>

                  <p className="rec-text">{rec.recommendation}</p>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="empty-state">
            <div className="empty-icon">💡</div>
            <h3>No critical recommendations required</h3>
            <p>All monitored KPIs are operating smoothly within target operational parameters.</p>
          </div>
        )}
      </div>
    </div>
  );
}
